// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Shared.Diagnostics;

namespace Microsoft.Extensions.AI;

/// <summary>
/// Provides extension methods for working with <see cref="IImageClient"/> instances.
/// </summary>
[Experimental("MEAI001")]
public static class ImageClientExtensions
{
    /// <summary>
    /// Generates images based on a text prompt.
    /// </summary>
    /// <param name="client">The image client.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The image generation options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <exception cref="ArgumentNullException"><paramref name="client"/> or <paramref name="prompt"/> are <see langword="null"/>.</exception>
    /// <returns>The images generated by the client.</returns>
    public static Task<ImageResponse> GenerateImagesAsync(
        this IImageClient client,
        string prompt,
        ImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(prompt);

        return client.GenerateImagesAsync(new ImageRequest(prompt), options, cancellationToken);
    }

    /// <summary>
    /// Generates images based on a text prompt with streaming updates.
    /// </summary>
    /// <param name="client">The image client.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The image generation options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <exception cref="ArgumentNullException"><paramref name="client"/> or <paramref name="prompt"/> are <see langword="null"/>.</exception>
    /// <returns>An async enumerable of image generation updates.</returns>
    public static IAsyncEnumerable<ImageResponseUpdate> GenerateImagesStreamingAsync(
        this IImageClient client,
        string prompt,
        ImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(prompt);

        return client.GenerateImagesStreamingAsync(new ImageRequest(prompt), options, cancellationToken);
    }

    /// <summary>
    /// Edits images based on original images and a text prompt.
    /// </summary>
    /// <param name="client">The image client.</param>
    /// <param name="originalImages">The images to base edits on.</param>
    /// <param name="prompt">The prompt to guide the image editing.</param>
    /// <param name="options">The image generation options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <exception cref="ArgumentNullException"><paramref name="client"/>, <paramref name="originalImages"/>, or <paramref name="prompt"/> are <see langword="null"/>.</exception>
    /// <returns>The images generated by the client.</returns>
    public static Task<ImageResponse> EditImagesAsync(
        this IImageClient client,
        IEnumerable<AIContent> originalImages,
        string prompt,
        ImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(originalImages);
        _ = Throw.IfNull(prompt);

        return client.GenerateImagesAsync(new ImageRequest(prompt, originalImages), options, cancellationToken);
    }

    /// <summary>
    /// Edits a single image based on the original image and the specified prompt.
    /// </summary>
    /// <param name="client">The image client.</param>
    /// <param name="originalImage">The single image to base edits on.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The image generation options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <exception cref="ArgumentNullException"><paramref name="client"/>, <paramref name="originalImage"/>, or <paramref name="prompt"/> are <see langword="null"/>.</exception>
    /// <returns>The images generated by the client.</returns>
    public static Task<ImageResponse> EditImageAsync(
        this IImageClient client,
        DataContent originalImage,
        string prompt,
        ImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(originalImage);
        _ = Throw.IfNull(prompt);

        return client.EditImagesAsync([originalImage], prompt, options, cancellationToken);
    }

    /// <summary>
    /// Edits a single image based on a byte array and the specified prompt.
    /// </summary>
    /// <param name="client">The image client.</param>
    /// <param name="originalImageData">The byte array containing the image data to base edits on.</param>
    /// <param name="fileName">The filename for the image data.</param>
    /// <param name="prompt">The prompt to guide the image generation.</param>
    /// <param name="options">The image generation options to configure the request.</param>
    /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
    /// <exception cref="ArgumentNullException">
    /// <paramref name="client"/>, <paramref name="originalImageData"/>, <paramref name="fileName"/>, 
    /// or <paramref name="prompt"/> are <see langword="null"/>.
    /// </exception>
    /// <returns>The images generated by the client.</returns>
    public static Task<ImageResponse> EditImageAsync(
        this IImageClient client,
        byte[] originalImageData,
        string fileName,
        string prompt,
        ImageOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        _ = Throw.IfNull(client);
        _ = Throw.IfNull(originalImageData);
        _ = Throw.IfNull(fileName);
        _ = Throw.IfNull(prompt);

        // Infer media type from file extension
        string mediaType = GetMediaTypeFromFileName(fileName);

        var dataContent = new DataContent(originalImageData, mediaType) { Name = fileName };
        return client.EditImagesAsync([dataContent], prompt, options, cancellationToken);
    }

    /// <summary>
    /// Gets the media type based on the file extension.
    /// </summary>
    /// <param name="fileName">The filename to extract the media type from.</param>
    /// <returns>The media type corresponding to the file extension.</returns>
    private static string GetMediaTypeFromFileName(string fileName)
    {
        string extension = Path.GetExtension(fileName).ToUpperInvariant();
        return extension switch
        {
            ".PNG" => "image/png",
            ".JPG" or ".JPEG" => "image/jpeg",
            ".GIF" => "image/gif",
            ".BMP" => "image/bmp",
            ".WEBP" => "image/webp",
            ".TIFF" or ".TIF" => "image/tiff",
            ".SVG" => "image/svg+xml",
            _ => "image/png" // Default to PNG
        };
    }
}
